import express from 'express';
const app = express();

app.listen('3001', () => {
    console.log(`We are Successfully running at 3001`);
});
const data = [{
    "id": "6dab651a-dfb1-4adf-9cc3-3a5e9ec64855",
    "title": "Metal Fabricator",
    "description": "Sit natus ea libero nihil adipisci ea. Magnam harum assumenda non alias. Ipsum a quia accusantium numquam expedita et enim. Eum dolorum rem delectus illum illum voluptatem.",
    "company": "Robel-Haag",
    "location": "Cotabato City, Palau",
    "salary_from": 59484,
    "salary_to": 80493,
    "employment_type": "Contract Developer",
    "application_deadline": "Mon, 10/07/2002",
    "qualifications": "[\"2 years of Git experience\",\"Master of TypeScript\",\"Solid understanding of AWS\",\"Expert in Docker\"]",
    "contact": "728-762-526",
    "job_category": "Front-end Developer",
    "is_remote_work": 1,
    "number_of_opening": 8,
    "created_at": "Sun, 10/15/2023",
    "updated_at": "Sun, 10/15/2023"
},
{
    "id": "e3caf401-13b8-4609-b47e-44807f6d6573",
    "title": "Online Marketing Analyst",
    "description": "Reiciendis harum nisi totam ea consequatur quae cumque eligendi. Iusto quos perspiciatis sed architecto odit molestias. Consequatur quia quidem velit non. Aut consequatur aut distinctio aut sed modi consequatur voluptatibus.",
    "company": "Weissnat Group",
    "location": "Meycauayan, Mozambique",
    "salary_from": 57961,
    "salary_to": 96056,
    "employment_type": "Temporary Developer",
    "application_deadline": "Sun, 10/24/1971",
    "qualifications": "[\"3+ years in Python\",\"3 years in Node.js\",\"Advanced in Swift\",\"Solid understanding of AWS\"]",
    "contact": "345-857-802",
    "job_category": "Mobile App Developer",
    "is_remote_work": 1,
    "number_of_opening": 7,
    "created_at": "Sun, 10/15/2023",
    "updated_at": "Sun, 10/15/2023"
},
{
    "id": "41563207-cc2d-4947-8ea7-0fdfb8339e93",
    "title": "Private Detective and Investigator",
    "description": "Amet dolorem ea eos pariatur omnis similique. Corporis sit ipsa laborum saepe accusamus natus ullam eos. Ullam dolore sunt vitae autem ipsam. Nam voluptate quos et.",
    "company": "Cummerata-Treutel",
    "location": "Batac, Palau",
    "salary_from": 71403,
    "salary_to": 102053,
    "employment_type": "Consultant",
    "application_deadline": "Thu, 06/10/1971",
    "qualifications": "[\"Proficient in SQL\",\"2+ years in Ruby\",\"Expert in Docker\",\"Proficient in MongoDB\"]",
    "contact": "013-197-228",
    "job_category": "DevOps Engineer",
    "is_remote_work": 0,
    "number_of_opening": 1,
    "created_at": "Sun, 10/15/2023",
    "updated_at": "Sun, 10/15/2023"
},
{
    "id": "b6707a23-0753-4fd8-9d0d-a50f4d9f684f",
    "title": "TSA",
    "description": "Quia praesentium accusamus deserunt vitae unde rerum. Et dicta dicta rerum consequuntur perspiciatis error quo. Sunt natus recusandae assumenda aliquam nisi esse asperiores.",
    "company": "Pfannerstill Ltd",
    "location": "Masbate City, Central African Republic",
    "salary_from": 68297,
    "salary_to": 97658,
    "employment_type": "Temporary Developer",
    "application_deadline": "Tue, 04/24/2001",
    "qualifications": "[\"Skilled in React\",\"Advanced in Swift\",\"Proficient in MongoDB\",\"Skilled in GraphQL\"]",
    "contact": "236-451-180",
    "job_category": "UI/UX Designer",
    "is_remote_work": 0,
    "number_of_opening": 4,
    "created_at": "Sun, 10/15/2023",
    "updated_at": "Sun, 10/15/2023"
},
{
    "id": "bf7b5592-3619-449c-83a6-7208d4d89ff4",
    "title": "Supervisor Correctional Officer",
    "description": "Rerum veniam harum sapiente nostrum et eligendi. Temporibus laboriosam dignissimos qui eos enim et voluptate rerum. Molestiae eius laborum et doloremque repudiandae neque. Autem explicabo in asperiores illo.",
    "company": "Jenkins PLC",
    "location": "Marikina, Cuba",
    "salary_from": 73268,
    "salary_to": 105321,
    "employment_type": "Co-founder/Technical Partner",
    "application_deadline": "Mon, 10/05/1992",
    "qualifications": "[\"Advanced HTML\\/CSS\",\"4+ years in C++\",\"Master of TypeScript\",\"Proficient in Kotlin\"]",
    "contact": "303-679-261",
    "job_category": "UI/UX Designer",
    "is_remote_work": 1,
    "number_of_opening": 1,
    "created_at": "Sun, 10/15/2023",
    "updated_at": "Sun, 10/15/2023"
},
{
    "id": "093caa12-5cd3-49d0-8421-279965d874e3",
    "title": "Foundry Mold and Coremaker",
    "description": "Velit temporibus saepe corrupti qui. Incidunt nostrum itaque nisi nesciunt incidunt. Explicabo voluptate rem nihil at. Tempore placeat tempora aliquid qui.",
    "company": "Grady, Harvey and Friesen",
    "location": "La Carlota, Reunion",
    "salary_from": 71706,
    "salary_to": 118085,
    "employment_type": "In-house Developer for Non-Tech Company",
    "application_deadline": "Sat, 04/10/1982",
    "qualifications": "[\"Expert in JavaScript\",\"Proficient in SQL\",\"3 years in Node.js\",\"Solid understanding of AWS\"]",
    "contact": "992-941-378",
    "job_category": "Back-end Developer",
    "is_remote_work": 1,
    "number_of_opening": 5,
    "created_at": "Sun, 10/15/2023",
    "updated_at": "Sun, 10/15/2023"
},
{
    "id": "3a21d97e-7b02-4fd6-a419-1792c2e99906",
    "title": "Motorboat Mechanic",
    "description": "Deleniti occaecati consequuntur autem laboriosam ea nobis. Cupiditate laborum illum autem nihil similique illo. Est itaque iste enim et neque. Explicabo similique architecto officiis sed minus laborum. Quod nostrum eos eos in vel.",
    "company": "Grimes, Yost and Bayer",
    "location": "San Jose, Saint Lucia",
    "salary_from": 63253,
    "salary_to": 114920,
    "employment_type": "Freelance Developer",
    "application_deadline": "Mon, 05/29/1995",
    "qualifications": "[\"3+ years in Python\",\"2 years of Git experience\",\"3+ years in Angular\",\"Proficient in MongoDB\"]",
    "contact": "174-843-942",
    "job_category": "Data Scientist",
    "is_remote_work": 0,
    "number_of_opening": 4,
    "created_at": "Sun, 10/15/2023",
    "updated_at": "Sun, 10/15/2023"
},
{
    "id": "77fe3ed3-bc4c-4fc4-a028-58b8d676f5e0",
    "title": "Nuclear Power Reactor Operator",
    "description": "Nihil ipsam voluptas quam velit adipisci voluptatum iusto. Eos esse consequatur sunt quia quo accusantium similique. Saepe quia dolore eaque dignissimos doloribus qui praesentium.",
    "company": "Langosh, Fritsch and Renner",
    "location": "Tarlac City, Comoros",
    "salary_from": 56405,
    "salary_to": 97931,
    "employment_type": "Part-time Developer",
    "application_deadline": "Mon, 12/29/2015",
    "qualifications": "[\"4+ years in C++\",\"Expert in Docker\",\"Proficient in MongoDB\",\"Skilled in GraphQL\"]",
    "contact": "138-234-877",
    "job_category": "Data Scientist",
    "is_remote_work": 0,
    "number_of_opening": 2,
    "created_at": "Sun, 10/15/2023",
    "updated_at": "Sun, 10/15/2023"
}];
app.get('/jobs', (req, res) => {
    res.send(data);
});